# Generated by Django 4.0.7 on 2022-09-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.PositiveIntegerField()),
                ('protien', models.PositiveIntegerField()),
                ('fat', models.PositiveIntegerField()),
                ('carbo', models.PositiveIntegerField()),
                ('cl', models.PositiveIntegerField()),
                ('iron', models.PositiveIntegerField()),
                ('sodium', models.PositiveIntegerField()),
                ('vA', models.PositiveIntegerField()),
                ('vB', models.PositiveIntegerField()),
                ('vB1', models.PositiveIntegerField()),
                ('vB2', models.PositiveIntegerField()),
                ('vC', models.PositiveIntegerField()),
            ],
        ),
    ]
