# Generated by Django 4.0.7 on 2022-09-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
