# Generated by Django 4.0.7 on 2022-09-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_remove_ingredient_vb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='energy',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
