# Generated by Django 4.0.7 on 2022-09-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hero_bmi_alter_hero_height_alter_hero_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
