# Generated by Django 4.0.7 on 2022-09-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hero_height_alter_hero_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='Breakfast',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='Dinner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='Lunch',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
