# Generated by Django 4.0.7 on 2022-09-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hero_breakfast_hero_dinner_hero_lunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='Gym',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='Run',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='SleepEarly',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='WakeEarly',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='Workouthome',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
